"""create tables and initialize test data

Revision ID: da0799836132
Revises: 
Create Date: 2022-04-24 21:45:26.836673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0799836132'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    customer = op.create_table('customer',
                               sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                               sa.Column('name', sa.String(length=64), nullable=False),
                               sa.PrimaryKeyConstraint('id')
                               )
    room = op.create_table('room',
                           sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                           sa.Column('name', sa.String(length=64), nullable=False),
                           sa.PrimaryKeyConstraint('id'),
                           sa.UniqueConstraint('name')
                           )
    rack = op.create_table('rack',
                           sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                           sa.Column('name', sa.String(length=64), nullable=False),
                           sa.Column('size', sa.Integer(), nullable=False),
                           sa.Column('state', sa.String(length=64), nullable=False),
                           sa.Column('customer', sa.Integer(), nullable=True),
                           sa.Column('room_id', sa.Integer(), nullable=True),
                           sa.ForeignKeyConstraint(['customer'], ['customer.id'], ),
                           sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
                           sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # add test data to db
    op.bulk_insert(customer,
                   [
                       {'id': 1, 'name': 'Клиент-1'},
                       {'id': 2, 'name': 'Клиент-2'},
                       {'id': 3, 'name': 'Клиент-3'},
                   ])

    op.bulk_insert(room,
                   [
                       {'id': 1, 'name': 'Room1'},
                       {'id': 2, 'name': 'Room2'},
                       {'id': 3, 'name': 'Room3'},
                       {'id': 4, 'name': 'Room4'},
                   ])

    op.bulk_insert(rack,
                   [
                       {'id': 1, 'name': 'Rack1', 'size': 42, 'state': 'occupied', 'customer': 1, 'room_id': 1},
                       {'id': 2, 'name': 'Rack2', 'size': 42, 'state': 'occupied', 'customer': 2, 'room_id': 1},
                       {'id': 3, 'name': 'Rack3', 'size': 21, 'state': 'free', 'customer': 3, 'room_id': 1},
                       {'id': 4, 'name': 'Rack4', 'size': 42, 'state': 'occupied', 'customer': 1, 'room_id': 2},
                       {'id': 5, 'name': 'Rack5', 'size': 42, 'state': 'free', 'customer': 1, 'room_id': 2},
                       {'id': 6, 'name': 'Rack6', 'size': 47, 'state': 'free', 'customer': 2, 'room_id': 3},
                       {'id': 7, 'name': 'Rack7', 'size': 42, 'state': 'occupied', 'customer': 1, 'room_id': 3},
                       {'id': 8, 'name': 'Rack8', 'size': 21, 'state': 'occupied', 'customer': 1, 'room_id': 3},
                   ])


def downgrade():
    pass
